id: I928E7532
legacy_id: P010562
ocr_import_info:
  bdrc_scan_id: W23632
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T18:28:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:25:31.196330+00:00'
last_modified: 2022-09-02 09:25:55.786159
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23632
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23632
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་འགྲེལ་པ་རབ་ཏུ་བྱ་བ་གསལ་ལྡན། （བླ་བྲང་པར་མ།）
  author: འདར་པ་ལོ་ཙཱ་བ་ངག་དབང་ཕུན་ཚོགས་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.534411734755762
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I1KG10589:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10589
      total_pages: 304
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10589.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.534411734755762
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
