id: I928E7532
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:30:25+00:00'
last_modified: '2022-06-08T14:30:45.274255+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23632
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་འགྲེལ་པ་རབ་ཏུ་བྱ་བ་གསལ་ལྡན། （བླ་བྲང་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9347':
      image_group_id: I1KG10589
      title: ''
      total_pages: 304
      order: 1
      base_file: 9347.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
