id: P010562
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:56:07.930576
source_metadata:
  id: bdr:W23632
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་འགྲེལ་པ་རབ་ཏུ་བྱ་བ་གསལ་ལྡན། （བླ་བྲང་པར་མ།）
  author: ''
  volumes:
    cd60dd23410b491887b4b75f10644eec:
      image_group_id: I1KG10589
      title: ''
      volume_number: 1
      total_pages: 304
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
